sudo: false
dist: trusty
language: ruby
rvm: 2.6.1
cache: bundler
branches:
  only: master
bundler_args: --without production --retry=6
addons:
 postgresql: 9.6
env:
  global:
    - OX_AR_DB_USER=postgres
    - OX_AR_DB_PASS=
    - OX_AR_TEST_DB=travis_ci_test
  - "RAILS_VERSION=5.2.4.3"
  - "RAILS_VERSION=6.1.1"
before_script: bundle exec rake --trace db:create db:schema:load db:seed
