sudo: false
dist: trusty
language: ruby
rvm: 2.3.7
cache: bundler
branches:
  only: master
bundler_args: --without production --retry=6
addons:
 postgresql: 9.6
env:
  global:
    - OX_AR_DB_USER=postgres
    - OX_AR_DB_PASS=
    - OX_AR_TEST_DB=travis_ci_test
before_script: bundle exec rake --trace db:create db:schema:load db:seed
